language: ruby
sudo: false
before_install:
  - gem install rouge
  - gem install json
  - gem install bundler
  - gem install kramdown
  - gem install therubyracer
  - gem install jekyll
  - gem install html-proofer
install: bundle install
script: bundle exec jekyll build -d _site
rvm:
  - 2.5.1
  - 2.5.2
