###########################################################################
# XMPP Site Configuration

title: "example.com Communication Service"
description: ""
url: "https://im.example.com"
name: "example.com"
baseurl: "im.example.com"
destination: "/var/www/im.example.com"

owner-name: "Matt Rude"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://mattrude.com/"
owner-xmpp: "matt@mattrude.com"
owner-twitter: "mdrude"
owner-github: "mattrude"

xmpp-url: "example.com" # The XMPP domain url
xmpp-host: "im.example.com" # The hostname of the server
xmpp-conference-url: "conference.example.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.example.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.example.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

server-features: 1
user-guide: 0

###########################################################################
# The below values should auto update

ejabberd-version:
ejabberd-gitversion:
ejabberd-upload-days:
ejabberd-upload-fsize:

fingerprints: 1
fingerprint-expires: 
fingerprint-im-expires:
fingerprint-conference-expires:
fingerprint-proxy-expires:
fingerprint-upload-expires:
fingerprint-sha1:
fingerprint-sha256:
fingerprint-im-sha1:
fingerprint-im-sha256:
fingerprint-conference-sha1:
fingerprint-conference-sha256:
fingerprint-proxy-sha1:
fingerprint-proxy-sha256:
fingerprint-upload-sha1:
fingerprint-upload-sha256:

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

include:
- .well-known/host-meta

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less
- site-updater.sh
- update-site-certs.sh

plugins:
- jekyll-sitemap
  #- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
