###########################################################################
# XMPP Site Configuration

title: "example.com Communication Service"
description: ""
url: "https://im.example.com"
name: "example.com"
baseurl: "im.example.com"
destination: "/var/www/im.example.com"

owner-name: "Joe User"
owner-pgpkey: "0xc4909ee495b0761f"
owner-url: "https://example.com/"
owner-xmpp: "user@example.com"
#owner-email: "user@example.com"
owner-twitter: "mdrude"
owner-github: "example"

xmpp-url: "example.com" # The XMPP domain url
xmpp-host: "im.example.com" # The hostname of the server
xmpp-conference-url: "conference.example.com" # Multi-User Chat xep-0045
xmpp-proxy-url: "proxy.example.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)
xmpp-upload-url: "upload.example.com" # XEP-0065: SOCKS5 Bytestreams (Proxy)

server-features: 1
user-guide: 1

###########################################################################
# The below values should auto update

ejabberd-version: "18.06.95"
ejabberd-gitversion: "0146189b6551c1562823ed43ab3d3bca90a3a19b"
ejabberd-upload-days: "90"
ejabberd-upload-fsize: "1 GB"

fingerprints: 1
fingerprint-expires: "Sep 18 00:00:15 2018 GMT"
fingerprint-im-expires: "Sep 19 06:42:39 2018 GMT"
fingerprint-conference-expires: "Sep 19 06:42:39 2018 GMT"
fingerprint-proxy-expires: "Sep 19 06:42:39 2018 GMT"
fingerprint-upload-expires: "Sep 19 06:42:39 2018 GMT"
fingerprint-sha1: "15:F5:30:A6:C5:B5:BE:A6:50:82:45:25:5B:0F:01:F7:74:DF:5D:86"
fingerprint-sha256: "78:E0:EA:9F:77:F8:5F:77:79:F5:8A:DA:95:F3:EF:B2:50:FE:63:8D:5A:A2:73:E1:2C:1E:F3:E3:F1:40:AE:78"
fingerprint-im-sha1: "73:13:23:6F:F7:C9:E2:BD:7C:49:7C:A0:7E:50:FF:67:57:6B:EC:1B"
fingerprint-im-sha256: "0D:1D:06:6F:C1:2B:58:BB:FA:F7:DF:25:3E:CD:78:81:65:38:79:12:ED:E3:CF:CE:FD:E2:CF:A1:1C:C4:61:7D"
fingerprint-conference-sha1: "73:13:23:6F:F7:C9:E2:BD:7C:49:7C:A0:7E:50:FF:67:57:6B:EC:1B"
fingerprint-conference-sha256: "0D:1D:06:6F:C1:2B:58:BB:FA:F7:DF:25:3E:CD:78:81:65:38:79:12:ED:E3:CF:CE:FD:E2:CF:A1:1C:C4:61:7D"
fingerprint-proxy-sha1: "73:13:23:6F:F7:C9:E2:BD:7C:49:7C:A0:7E:50:FF:67:57:6B:EC:1B"
fingerprint-proxy-sha256: "0D:1D:06:6F:C1:2B:58:BB:FA:F7:DF:25:3E:CD:78:81:65:38:79:12:ED:E3:CF:CE:FD:E2:CF:A1:1C:C4:61:7D"
fingerprint-upload-sha1: "73:13:23:6F:F7:C9:E2:BD:7C:49:7C:A0:7E:50:FF:67:57:6B:EC:1B"
fingerprint-upload-sha256: "0D:1D:06:6F:C1:2B:58:BB:FA:F7:DF:25:3E:CD:78:81:65:38:79:12:ED:E3:CF:CE:FD:E2:CF:A1:1C:C4:61:7D"

xep-0045: 1
xep-0065: 1
xep-0115: 1
xep-0160: 1
xep-0163: 1
xep-0191: 1
xep-0198: 1
xep-0280: 1
xep-0313: 1
xep-0352: 1
xep-0357: 1
xep-0363: 1
xep-0368: 1
xep-0384: 1
xep-0398: 1

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- css/syntax.less
- css/site.less
- css/small.less

plugins:
- jekyll-sitemap
  #- jekyll-press

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
